services:
  user-mongo:
    image: mongo:latest
    ports:
      - "${USER_MONGO_PORT}:27017"
    volumes:
      - user-mongo-data:/data/db
    command: mongod --auth --wiredTigerCacheSizeGB=0.25
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${USER_MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${USER_MONGO_DB}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
  notification-mongo:
    image: mongo:latest
    ports:
      - "${NOTIFICATION_MONGO_PORT}:27017"
    volumes:
      - notification-mongo-data:/data/db
    command: mongod --auth --wiredTigerCacheSizeGB=0.25
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${NOTIFICATION_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${NOTIFICATION_MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${NOTIFICATION_MONGO_DB}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
  trip-mongo:
    image: mongo:latest
    ports:
      - "${TRIP_MONGO_PORT}:27017"
    volumes:
      - trip-mongo-data:/data/db
    command: mongod --auth --wiredTigerCacheSizeGB=0.25
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${TRIP_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${TRIP_MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${TRIP_MONGO_DB}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.3'
volumes:
  user-mongo-data:
  notification-mongo-data:
  trip-mongo-data:
  redis-data: