services:
  # Database Services
  user-mongo:
    image: mongo:latest
    ports:
      - "${USER_MONGO_PORT:-27017}:27017"
    volumes:
      - user-mongo-data:/data/db
    command: mongod --auth --wiredTigerCacheSizeGB=0.25
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER_MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${USER_MONGO_PASSWORD:-secure_password}
      - MONGO_INITDB_DATABASE=${USER_MONGO_DB:-sober-user}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
    networks:
      - sober-network
    restart: unless-stopped

  notification-mongo:
    image: mongo:latest
    ports:
      - "${NOTIFICATION_MONGO_PORT:-27018}:27017"
    volumes:
      - notification-mongo-data:/data/db
    command: mongod --auth --bind_ip_all --wiredTigerCacheSizeGB=0.25
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${NOTIFICATION_MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${NOTIFICATION_MONGO_PASSWORD:-secure_password}
      - MONGO_INITDB_DATABASE=${NOTIFICATION_MONGO_DB:-sober-notification}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
    networks:
      - sober-network
    restart: unless-stopped

  trip-mongo:
    image: mongo:latest
    ports:
      - "${TRIP_MONGO_PORT:-27019}:27017"
    volumes:
      - trip-mongo-data:/data/db
    command: mongod --auth --wiredTigerCacheSizeGB=0.25
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${TRIP_MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${TRIP_MONGO_PASSWORD:-secure_password}
      - MONGO_INITDB_DATABASE=${TRIP_MONGO_DB:-sober-trip}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
    networks:
      - sober-network
    restart: unless-stopped

  promotion-mongo:
    image: mongo:latest
    ports:
      - "${PROMOTION_MONGO_PORT:-27020}:27017"
    volumes:
      - promotion-mongo-data:/data/db
    command: mongod --auth --wiredTigerCacheSizeGB=0.25
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PROMOTION_MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${PROMOTION_MONGO_PASSWORD:-secure_password}
      - MONGO_INITDB_DATABASE=${PROMOTION_MONGO_DB:-promotion}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
    networks:
      - sober-network
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-secure_redis_password} --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.3'
    networks:
      - sober-network
    restart: unless-stopped

  customer-api-gateway:
    build:
      context: ../customer-api-gateway
      dockerfile: dockerfile
    ports:
      - "${API_GATEWAY_PORT:-3000}:3000"
    env_file:
      - ../customer-api-gateway/.env
    depends_on:
      - user-mongo
    networks:
      - sober-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    restart: unless-stopped

  user-api:
    build:
      context: ../sober-user-api
      dockerfile: Dockerfile
    ports:
      - "${USER_API_PORT:-3001}:3001"
    env_file:
      - ../sober-user-api/.env.docker
    depends_on:
      - user-mongo
      - redis
    networks:
      - sober-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    restart: unless-stopped
  promotion-api:
    build:
      context: ../1drive-promotion-api
      dockerfile: Dockerfile
    ports:
      - "${PROMOTION_API_PORT:-3002}:3000"
    environment:
      - ../1drive-promotion-api/.env.docker
    depends_on:
      - promotion-mongo
    networks:
      - sober-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    restart: unless-stopped

networks:
  sober-network:
    driver: bridge
    name: sober-network

volumes:
  user-mongo-data:
  notification-mongo-data:
  trip-mongo-data:
  redis-data: